### PR TITLE
Translations update from Weblate

### PR DESCRIPTION
**Pull request by weblate**
Translations update from [Weblate](https://hosted.weblate.org/projects/stellarium-mobile/app/) for Stellarium-mobile/app.

### CODE REVIEW

**Comment by fitojb** [comment]
The PR has been pending for months. Please merge it.

**Comment by fitojb** [comment]
Also, I recommend setting Weblate up so that it squashes commits by author, to avoid polluting the Git log.

**Comment by lduboeuf** [comment]
Oh i just discovered all your work, sorry for the long wait. I will merge it next week. Ping me if i forget

**Comment by lduboeuf** [comment]
Thank you all, and sorry for the long delay, i surely missed a notification from github. I will publish today

**Pull request merged**
